language: python
python:
    - "2.7"
    
# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"    

env:
    - PLATFORMIO_CI_SRC=examples/ir_control
    - PLATFORMIO_CI_SRC=examples/random_walk
install:
    - pip install -U platformio

script:
  - platformio lib --global install z3t0/Arduino-IRremote
  - platformio ci --lib="." --board=uno
